mentalray:
  name: Mental Ray
  show: false
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/mayatomr/%ST_MAYA_MR%/win/%ST_MAYA%/modules'
      versions:
        '3.12.1.18':
          env:
            ST_MAYA_MR: '3.12.1.18'
          path:
            linux: /
            mac: /
            win32: /
          versions:
arnold:
  name: Arnold
  show: false
  env:
    solidangle_LICENSE: ''
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/mtoa/%ST_MTOA%/win/%ST_MAYA%'
      versions:
        1.0.0.RC1:
          env:
            ST_MTOA: '1.0.0.RC1'
          path:
            linux: /
            mac: /
            win32: /
          versions:
        1.1.0.4:
          env:
            ST_MTOA: '1.1.0.4'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
        1.1.1.0:
          env:
            ST_MTOA: '1.1.1.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
        1.2.0.8:
          env:
            ST_MTOA: '1.2.0.8'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
        1.3.0.0:
          env:
            ST_MTOA: '1.3.0.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2017'
    softimage:
      versions:
        3.2.0:
          env:
            XSI_PLUGINS: '%GSROOT%/bin/arnold/softimage/%ST_SITOA%/%ST_SOFTIMAGE%'
            ST_SITOA: '3.2.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
crate:
  name: Exocortex Crate
  show: false
  env:
    EXOCORTEX_LICENSE: ''
    MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/crate/%ST_CRATE%/win/%ST_MAYA%'
  packages:
    maya:
      versions:
        '1.1.145':
          env:
            ST_CRATE: '1.1.145'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/crate/1.1.145/win/%ST_MAYA%'
          versions:
          - '2015'
        '1.1.148':
          env:
            ST_CRATE: '1.1.145'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/crate/1.1.148/win/%ST_MAYA%'
          versions:
          - '2015'
          - '2016.5'
        '1.1.150':
          env:
            ST_CRATE: '1.1.145'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/crate/1.1.150/win/%ST_MAYA%'
          versions:
          - '2015'
          - '2016.5'
vray:
  name: vray
  show: false
  env:
    #GS_MAYA_AUTOLOAD: 'vrayformaya'
    VRAY_AUTH_CLIENT_FILE_PATH: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%/conf'
    MAYA_RENDER_DESC_PATH: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%/maya_bin/rendererDesc'
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%'
      versions:
        '2.40.01':
          env:
            ST_MAYA_VRAY: '2.40.01'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%'
          versions:
        '3.30.02':
          env:
            ST_MAYA_VRAY: '3.30.02'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%'
          versions:
          - '2015'
          - '2016.5'
        '3.40.06':
          env:
            ST_MAYA_VRAY: '3.40.06'
          path:
            linux: /
            mac: /
            win32: '%GSROOT%/bin/external/maya/modules/vrayformaya/%ST_MAYA_VRAY%/win/%ST_MAYA%'
          versions:
          - '2016.5'
          - '2017'
realflow:
  name: realflow
  show: false
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/realflow/%ST_REALFLOW%/win/%ST_MAYA%'
      versions:
        '2015.0.0.9':
          env:
            ST_REALFLOW: '2015.0.0.9'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
zync:
  name: zync
  show: false
  env:
    ZYNC_API_DIR: '%GSROOT%/lib/python/zync-python'
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/zync/%ST_MAYA_ZYNC%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/zync/%ST_MAYA_ZYNC%/win/%ST_MAYA%/shelves'
      versions:
        '1.2.5':
          env:
            ST_MAYA_ZYNC: '1.2.5'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
advancedSkeleton:
  name: advancedSkeleton
  show: true
  packages:
    maya:
      env:
        #MAYA_SCRIPT_PATH: '%GSROOT%/bin/external/maya/modules/AdvancedSkeleton/%ST_ADVSKEL%/win/%ST_MAYA%/scripts'
        #XMB_LANG_PATH: '%GSROOT%/bin/external/maya/modules/AdvancedSkeleton/%ST_ADVSKEL%/win/%ST_MAYA%/icons'
        #PATH: '%GSROOT%/bin/external/maya/modules/AdvancedSkeleton/%ST_ADVSKEL%/win/%ST_MAYA%/bin'
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/AdvancedSkeleton/%ST_ADVSKEL%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/AdvancedSkeleton/%ST_ADVSKEL%/win/%ST_MAYA%/shelves'
      versions:
        '5.250':
          env:
            ST_ADVSKEL: '5.250'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '5.240':
          env:
            ST_ADVSKEL: '5.240'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '4.160':
          env:
            ST_ADVSKEL: '4.160'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
soup:
  name: soup
  show: false
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/SOuP/%ST_SOUP%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/SOuP/%ST_SOUP%/win/%ST_MAYA%/shelves'
      versions:
        '2016.06.01':
          env:
            ST_SOUP: '2016.06.01'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
        '2016.10.08':
          env:
            ST_SOUP: '2016.10.08'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2016'
          - '2017'
fumefx:
  name: fumefx
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/fumefx/%ST_FUMEFX%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/fumefx/%ST_FUMEFX%/win/%ST_MAYA%/shelves'
      versions:
        '4.0.3':
          env:
            ST_FUMEFX: '4.0.3'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '4.0.0':
          env:
            ST_FUMEFX: '4.0.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
fracturefx:
  name: fracturefx
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/fracturefx/%ST_FRACFX%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/fracturefx/%ST_FRACFX%/win/%ST_MAYA%/shelves'
        FX_LCN_FILE: '%GSROOT%/bin/external/maya/modules/fracturefx/%ST_FRACFX%/win/%ST_MAYA%/config/fxlcn'
      versions:
        '1.9.6':
          env:
            ST_FRACFX: '1.9.6'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '1.9.1':
          env:
            ST_FRACFX: '1.9.6'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
krakatoa:
  name: krakatoa
  show: false
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/krakatoa/%ST_KRAKATOA%/win/%ST_MAYA%'
        #MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/krakatoa/%ST_KRAKATOA%/win/%ST_MAYA%/shelves'
        THINKBOX_LICENSE_FILE: '@laxlic01'
      versions:
        '2.6.3':
          env:
            ST_KRAKATOA: '2.6.3'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2017'
        '2.6.2':
          env:
            ST_KRAKATOA: '2.6.2'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '2.4.3.59396':
          env:
            ST_KRAKATOA: '2.4.3.59396'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
bonustools:
  name: bonustools
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/bonustools/%ST_MAYA_BT%/win/%ST_MAYA%'
      versions:
        '17.0.1':
          env:
            ST_MAYA_BT: '17.0.1'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
ideform:
  name: ideform
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/ideform/%ST_IDEFORM%/win/%ST_MAYA%'
      versions:
        '1.5.1':
          env:
            ST_IDEFORM: '1.5.1'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '1.5.0':
          env:
            ST_IDEFORM: '1.5.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '1.0.0':
          env:
            ST_IDEFORM: '1.0.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
partio:
  name: partio
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/partio/%ST_PARTIO%/win/%ST_MAYA%'
      versions:
        '0.9.6':
          env:
            ST_PARTIO: '0.9.6'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
phoenixfd:
  name: phoenixfd
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/phoenixfd/%ST_PHOENIX%/win/%ST_MAYA%'
        VRAY_AUTH_CLIENT_FILE_PATH: '%GSROOT%/bin/external/maya/modules/phoenixfd/%ST_PHOENIX%/win/%ST_MAYA%/conf'
      versions:
        '2.25.8':
          env:
            ST_PHOENIX: '2.25.8'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '3.03.00':
          env:
            ST_PHOENIX: '3.03.00'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
nimbletools:
  name: nimbletools
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/nimbletools/%ST_NIMBLE%/win/%ST_MAYA%'
      versions:
        '1.2.1':
          env:
            ST_NIMBLE: '1.2.1'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
ornatrix:
  name: ornatrix
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/ornatrix/%ST_ORNATRIX%/win/%ST_MAYA%'
      versions:
        '1.1.3.9340':
          env:
            ST_ORNATRIX: '1.1.3.9340'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
redshift:
  name: redshift
  show: true
  env:
    redshift_LICENSE: '5057@laxlic01'
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/redshift/%ST_MAYA_REDSHIFT%/win/%ST_MAYA%'
        MAYA_RENDER_DESC_PATH: '%GSROOT%/bin/external/maya/modules/redshift/%ST_MAYA_REDSHIFT%/win/%ST_MAYA%/bin/rendererDesc'
      versions:
        '2.5.52':
          env:
            ST_MAYA_REDSHIFT: '2.5.52'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2017'
        '2.5.13':
          env:
            ST_MAYA_REDSHIFT: '2.5.13'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '2.0.93':
          env:
            ST_MAYA_REDSHIFT: '2.0.93'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
        '2.0.70':
          env:
            ST_MAYA_REDSHIFT: '2.0.70'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
    cinema4d:
      env:
        REDSHIFT_COREDATAPATH: '%GSROOT%/bin/external/cinema4d/plugins/redshift/%ST_C4D_REDSHIFT%/%ST_C4D%/core'
        REDSHIFT_LOCALDATAPATH: '%GSROOT%/bin/external/cinema4d/plugins/redshift/%ST_C4D_REDSHIFT%/%ST_C4D%/core'
        REDSHIFT_PLUG_IN_PATH: '%GSROOT%/bin/external/cinema4d/plugins/redshift/%ST_C4D_REDSHIFT%/%ST_C4D%'
        C4D_PLUGINS_DIR: '%GSROOT%/bin/external/cinema4d/plugins/redshift/%ST_C4D_REDSHIFT%/%ST_C4D%'
        PATH: '%REDSHIFT_COREDATAPATH%/bin'
      versions:
        '2.5.13':
          env:
            ST_C4D_REDSHIFT: '2.5.13'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - 'R18'
        '2.0.83':
          env:
            ST_C4D_REDSHIFT: '2.0.83'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - 'R18'
be_openvdb:
  name: be_openvdb
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/be_openvdb/%ST_MAYA_OVDB%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/be_openvdb/%ST_MAYA_OVDB%/win/%ST_MAYA%/shelves'
      versions:
        '1.0':
          env:
            ST_MAYA_OVDB: '1.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2016'
          - '2016.5'
          - '2017'
slib:
  name: slib
  show: true
  packages:
    maya:
      versions:
        '2.02':
          env:
            MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/slib/2.02/win/%ST_MAYA%'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
animschoolpicker:
  name: animschoolpicker
  show: true
  packages:
    maya:
      versions:
        '1.4.6':
          env:
            MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/animschoolpicker/1.4.6/win/%ST_MAYA%'
            MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/animschoolpicker/1.4.6/win/%ST_MAYA%/shelves'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
studiolibrary:
  name: studiolibrary
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/studiolibrary/%ST_STUDIOLIB%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/studiolibrary/%ST_STUDIOLIB%/win/%ST_MAYA%/shelves'
      versions:
        '1.26.2':
          env:
            ST_STUDIOLIB: '1.26.2'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
substance:
  name: substance
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/substance/%ST_SUBSTANCE%/win/%ST_MAYA%'
      versions:
        '1.2.2.0':
          env:
            ST_SUBSTANCE: '1.2.2.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
elementacular:
  name: elementacular
  show: true
  packages:
    maya:
      env:
        MAYA_MODULE_PATH: '%GSROOT%/bin/external/maya/modules/elementacular/%ST_ELEMENTACULAR%/win/%ST_MAYA%'
        MAYA_SHELF_PATH: '%GSROOT%/bin/external/maya/modules/elementacular/%ST_ELEMENTACULAR%/win/%ST_MAYA%/shelves'
      versions:
        '1.5.0':
          env:
            ST_ELEMENTACULAR: '1.5.0'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '2015'
          - '2016.5'
          - '2017'
octane:
  name: octane
  show: true
  packages:
    cinema4d:
      env:
        C4D_PLUGINS_DIR: '%GSROOT%/bin/external/cinema4d/plugins/c4doctane/%ST_C4D_OCTANE%/%ST_C4D%'
      versions:
        '3.05.3':
          env:
            ST_C4D_OCTANE: '3.05.3'
          path:
            mac: /
            win32: /
          versions:
          - R17
          - R18
        '3.03.2':
          env:
            ST_C4D_OCTANE: '3.03.2'
          path:
            mac: /
            win32: /
          versions:
          - 'R17'
x-particles:
  name: x-particles
  show: true
  packages:
    cinema4d:
      env:
        C4D_PLUGINS_DIR: '%GSROOT%/bin/external/cinema4d/plugins/x-particles/%ST_C4D_XPART%/%ST_C4D%'
      versions:
        '3.5.0391':
          env:
            ST_C4D_XPART: '3.5.0391'
          path:
            mac: /
            win32: /
          versions:
          - 'R17'
          - 'R18'
qcmds:
  name: qcmds
  show: true
  packages:
    cinema4d:
      env:
        C4D_PLUGINS_DIR: '%GSROOT%/bin/external/cinema4d/plugins/qcmds/%ST_QCMDS%/%ST_C4D%'
      versions:
        '0.21':
          env:
            ST_QCMDS: '0.21'
          path:
            mac: /
            win32: /
          versions:
          - 'R17'
neatvideo:
  name: neatvideo
  show: true
  packages:
    nuke:
      env:
        ST_NUKE_PLUGINS: '%GSROOT%/bin/external/nuke/plugins/neatvideo/%ST_NEATVID%/%ST_NUKE%'
      versions:
        '4.0.9':
          env:
            ST_NEATVID: '4.0.9'
          path:
            linux: /
            mac: /
            win32: /
          versions:
          - '10.0'
          - '9.0'
          - '8.0'